VMs have already TRIM enabled by default, but dom0 doesn't. There are
some security implications (read for example `​this
article <http://asalor.blogspot.com/2011/08/trim-dm-crypt-problems.html>`__),
but IMO not very serious.

To enable TRIM in dom0 you need:

#. Get your LUKS device UUID:

   .. code:: wiki

       ls /dev/mapper/luks-*

#. Add entry to ``/etc/crypttab`` (replace luks-<UUID> with the device
   name and the <UUID> with UUID alone):

   .. code:: wiki

       luks-<UUID> UUID=<UUID> none allow-discards

#. Add ``rd.luks.allow-discards=1`` to kernel cmdline
   (``/etc/default/grub``, GRUB\_CMDLINE\_LINUX line)
#. Rebuild grub config (``grub2-mkconfig -o /boot/grub2/grub.cfg``)
#. Rebuild initrd **in hostonly mode**:

   .. code:: wiki

       dracut -H -f

#. Add "discard" option to ``/etc/fstab`` for root device
#. Reboot the system, verify that allow-discards is really enabled
   (``dmsetup table``)

There is a `​bug affecting allow-discards
option <https://bugzilla.redhat.com/show_bug.cgi?id=890533>`__, once it
will be fixed, first two steps will be no longer needed.
