QVM-tools:

-  `qubes-dom0-network-via-netvm </wiki/Dom0Tools/QubesDom0NetworkViaNetvm>`__
-  `qubes-dom0-update </wiki/Dom0Tools/QubesDom0Update>`__
-  `qubes-prefs </wiki/Dom0Tools/QubesPrefs>`__
-  `qvm-add-appvm </wiki/Dom0Tools/QvmAddAppvm>`__
-  `qvm-add-template </wiki/Dom0Tools/QvmAddTemplate>`__
-  `qvm-backup-restore </wiki/Dom0Tools/QvmBackupRestore>`__
-  `qvm-backup </wiki/Dom0Tools/QvmBackup>`__
-  `qvm-block </wiki/Dom0Tools/QvmBlock>`__
-  `qvm-clone </wiki/Dom0Tools/QvmClone>`__
-  `qvm-create-default-dvm </wiki/Dom0Tools/QvmCreateDefaultDvm>`__
-  `qvm-create </wiki/Dom0Tools/QvmCreate>`__
-  `qvm-firewall </wiki/Dom0Tools/QvmFirewall>`__
-  `qvm-grow-private </wiki/Dom0Tools/QvmGrowPrivate>`__
-  `qvm-ls </wiki/Dom0Tools/QvmLs>`__
-  `qvm-kill </wiki/Dom0Tools/QvmKill>`__
-  `qvm-pci </wiki/Dom0Tools/QvmPci>`__
-  `qvm-prefs </wiki/Dom0Tools/QvmPrefs>`__
-  `qvm-remove </wiki/Dom0Tools/QvmRemove>`__
-  `qvm-revert-template-changes </wiki/Dom0Tools/QvmRevertTemplateChanges>`__
-  `qvm-run </wiki/Dom0Tools/QvmRun>`__
-  `qvm-service </wiki/Dom0Tools/QvmService>`__
-  `qvm-shutdown </wiki/Dom0Tools/QvmShutdown>`__
-  `qvm-start </wiki/Dom0Tools/QvmStart>`__
-  `qvm-sync-appmenus </wiki/Dom0Tools/QvmSyncAppmenus>`__
-  `qvm-template-commit </wiki/Dom0Tools/QvmTemplateCommit>`__

