System Documentation for Developers
===================================

#. Fundamentals:

   #. Qubes OS Architecture v0.3
      `​(pdf) <http://files.qubes-os.org/files/doc/arch-spec-0.3.pdf>`__
      (The original 2009 document that started this all...)
   #. `Security-critical elements of Qubes
      OS </wiki/SecurityCriticalCode>`__
   #. Qubes RPC framework (qrexec):

      #. `The Qubes RPC/Service API </wiki/Qrexec>`__
      #. Example for writing a qrexec service in Qubes OS `​blog
         post <http://theinvisiblethings.blogspot.com/2013/02/converting-untrusted-pdfs-into-trusted.html>`__
      #. `qrexec implementation in Qubes
         R2 </wiki/Qrexec2Implementation>`__
      #. `qrexec implementation in Qubes
         R3/Odyssey </wiki/Qrexec3Implementation>`__

   #. `Qubes GUI virtualization protocol </wiki/GUIdocs>`__
   #. `Networking in Qubes </wiki/QubesNet>`__
   #. `Implementation of template sharing and
      updating </wiki/TemplateImplementation>`__

#. Services:

   #. `Inter-domain file copying </wiki/Qfilecopy>`__
   #. `Dynamic memory management in Qubes </wiki/Qmemman>`__
   #. `Implementation of DisposableVMs </wiki/DVMimpl>`__
   #. `​Article about disposable
      VMs <http://theinvisiblethings.blogspot.com/2010/06/disposable-vms.html>`__
   #. `Dom0 secure update mechanism </wiki/Dom0SecureUpdates>`__
   #. `VM secure update mechanism? </wiki/VMSecureUpdates>`__

#. Debugging:

   #. `Profiling python code </wiki/Profiling>`__
   #. `Test environment in separate machine for automatic
      tests </wiki/TestBench>`__
   #. `VM-dom0 internal configuration
      interface </wiki/SystemDoc/VMInterface>`__
   #. `Debugging Windows VMs </wiki/WindowsDebugging>`__

#. Building:

   #. `Building Qubes </wiki/QubesBuilder>`__
   #. `Development Workflow </wiki/DevelopmentWorkflow>`__
   #. `KDE Dom0 packages for Qubes </wiki/KdeDom0>`__
   #. `How to build Qubes installation
      ISO </wiki/InstallationIsoBuilding>`__
   #. `Building USB passthrough support (experimental) </wiki/USBVM>`__
   #. `Building a TemplateVM based on a new OS (ArchLinux
      example) </wiki/BuildingNonFedoraTemplate>`__
   #. `Building the Archlinux
      Template </wiki/BuildingArchlinuxTemplate>`__


