This is a test page
===================

Please ignore.

|No image "snapshot1.png" attached to TestTest|

.. |No image "snapshot1.png" attached to TestTest| image:: /chrome/common/attachment.png
   :target: /attachment/wiki/TestTest/snapshot1.png
