Qubes User Documentation
========================

#. **Basic Reading**

   #. `Getting Started </wiki/GettingStarted>`__
   #. `Security Guidelines </wiki/SecurityGuidelines>`__
   #. `Glossary of Qubes Terminology </wiki/Glossary>`__

#. **Dom0**

   #. `Dom0 Command-Line Tools </wiki/DomZeroTools>`__
   #. `Updating Software in dom0 </wiki/SoftwareUpdateDom0>`__
   #. `Copying Files to and from dom0 </wiki/CopyToDomZero>`__
   #. `Backup, Restoration, and Migration </wiki/BackupRestore>`__
   #. `Qubes Policy for InterVM Services? </wiki/QrexecPolicy>`__
   #. Advanced Topics

      #. `Installing Anti Evil Maid </wiki/AntiEvilMaid>`__
      #. `XFCE Installation in dom0 </wiki/UserDoc/XFCE>`__
      #. `Installing ZFS in Qubes </wiki/ZFS>`__

#. **DomUs**

   #. `DomU Command-Line Tools </wiki/VmTools>`__
   #. **Intra-VM Actions**

      #. `Enabling Fullscreen Mode </wiki/FullScreenMode>`__
      #. `Managing Application
         Shortcuts </wiki/ManagingAppVmShortcuts>`__

   #. **Inter-VM Actions**

      #. `Copying and Pasting Text Between Domains </wiki/CopyPaste>`__
      #. `Copying and Moving Files Between
         Domains </wiki/CopyingFiles>`__
      #. `Using GPG more securely in Qubes: Split GPG
         tutorial </wiki/UserDoc/SplitGpg>`__

   #. **NetVMs and ProxyVMs**

      #. `Understanding Qubes Firewall </wiki/QubesFirewall>`__
      #. `Understanding and Preventing Data Leaks </wiki/DataLeaks>`__
      #. `How to Install a Transparent Tor ProxyVM
         (TorVM) </wiki/UserDoc/TorVM>`__
      #. `How to set up a ProxyVM as a VPN Gateway </wiki/VPN>`__
      #. `Adding Bridge Support to the NetVM
         (EXPERIMENTAL) </wiki/NetworkBridgeSupport>`__
      #. External Links

         #. `​Creating Custom NetVMs and
            ProxyVMs <http://theinvisiblethings.blogspot.com/2011/09/playing-with-qubes-networking-for-fun.html>`__
         #. `​How to run TorBrowser using external tor proxy (from
            TorVM) <https://groups.google.com/group/qubes-devel/msg/34f67194d3422bfa>`__
         #. `​How to make proxy for individual tcp connection from
            networkless
            VM <https://groups.google.com/group/qubes-devel/msg/4ca950ab6d7cd11a>`__
         #. `​HTTP filtering proxy in Qubes firewall
            VM <https://groups.google.com/group/qubes-devel/browse_thread/thread/5252bc3f6ed4b43e/d881deb5afaa2a6c#39c95d63fccca12b>`__

   #. **TemplateVMs**

      #. `Updating and Installing Software in
         VMs </wiki/SoftwareUpdateVM>`__
      #. `Templates: Fedora - minimal </wiki/Templates/FedoraMinimal>`__
      #. `Templates: Debian </wiki/Templates/Debian>`__
      #. External Links

         #. `​Extending \`root.img\`
            Size <https://groups.google.com/group/qubes-devel/msg/9d1ac581236ca9b4>`__

   #. **DispVMs**

      #. `Disposable VMs </wiki/DisposableVms>`__
      #. `DispVM Customization </wiki/UserDoc/DispVMCustomization>`__

   #. **HVMs**

      #. `Resizing AppVM and HVM Disk Images </wiki/ResizeDiskImage>`__
      #. `Tips for Using Linux in an HVM </wiki/LinuxHVMTips>`__
      #. `Creating and Using HVM and Windows Domains (Qubes R2
         Only) </wiki/HvmCreate>`__
      #. External Links

         #. `​Creating Whonix HVMs in
            Qubes <https://www.whonix.org/wiki/Qubes>`__
         #. `​Creating NetBSD
            VM <https://groups.google.com/group/qubes-devel/msg/4015c8900a813985>`__

   #. **Windows VMs**

      #. `Installing and Using Windows-based AppVMs (Qubes R2 Beta 3 and
         Later) </wiki/WindowsAppVms>`__
      #. `Advanced options and troubleshooting of Qubes Tools for
         Windows </wiki/WindowsTools>`__

   #. Advanced Topics

      #. `Configuration files </wiki/UserDoc/ConfigFiles>`__
      #. `Qubes service framework </wiki/QubesService>`__
      #. `Note regarding password-less root access in
         VM </wiki/VMSudo>`__

#. **Hardware**

   #. `How to Mount USB Sticks to AppVMs </wiki/StickMounting>`__
   #. `Where are my external storage devices
      mounted? </wiki/ExternalDeviceMountPoint>`__
   #. `Assigning PCI Devices to AppVMs </wiki/AssigningDevices>`__
   #. `Enabling TRIM for SSD disks </wiki/DiskTRIM>`__
   #. `Configuring a Network Printer </wiki/NetworkPrinter>`__
   #. `Using External Audio Devices </wiki/ExternalAudio>`__
   #. Vendor-specific

      #. `How to install an Nvidia driver in
         dom0 </wiki/InstallNvidiaDriver>`__
      #. `Getting Sony Vaio Z laptop to work with
         Qubes </wiki/SonyVaioTinkering>`__

   #. External Links

      #. `​Installing on system with new AMD GPU (missing firmware
         problem) <https://groups.google.com/group/qubes-devel/browse_thread/thread/e27a57b0eda62f76>`__
      #. `​Solving problems with Macbook Air
         2012 <https://groups.google.com/group/qubes-devel/browse_thread/thread/b8b0d819d2a4fc39/d50a72449107ab21#8a9268c09d105e69>`__
      #. `​Booting with GRUB2 and
         GPT <https://groups.google.com/group/qubes-devel/browse_thread/thread/e4ac093cabd37d2b/d5090c20d92c4128#d5090c20d92c4128>`__


