Welcome to the Qubes Wiki
=========================

For Users
---------

-  `Installation guide </wiki/InstallationGuide>`__
-  `On digital signatures? </wiki/VeryfingSignatures>`__
-  `Documentation </wiki/UserDoc>`__
-  `FAQ </wiki/UserFaq>`__

For Developers
--------------

-  `Documentation </wiki/SystemDoc>`__
-  `Source Code </wiki/SourceCode>`__
-  `FAQ </wiki/DevelFaq>`__

Contact
-------

Mailing list
~~~~~~~~~~~~

Coming soon...

Project administrators
~~~~~~~~~~~~~~~~~~~~~~

-  Joanna Rutkowska
   <`​joanna@invisiblethingslab.com <mailto:joanna@invisiblethingslab.com>`__\ >
-  Rafal Wojtczuk
   <`​rafal@invisiblethingslab.com <mailto:rafal@invisiblethingslab.com>`__\ >

