Welcome to the Qubes Wiki
=========================

For Users
---------

-  `Qubes Security Goals </wiki/SecurityGoals>`__
-  `Installation guide </wiki/InstallationGuide>`__
-  `Hardware Compatibility List </wiki/HCL>`__
-  `On digital signatures and how to verify Qubes
   downloads </wiki/VerifyingSignatures>`__
-  `User Guide </wiki/UserDoc>`__
-  `FAQ </wiki/UserFaq>`__

For Developers
--------------

-  `Qubes Developer Documentation </wiki/SystemDoc>`__
-  `Ideas Incubator? </wiki/IdeasIncubator>`__
-  `Source Code </wiki/SourceCode>`__
-  `FAQ </wiki/DevelFaq>`__

-  `How can I contribute to the Qubes
   Project? </wiki/ContributingHowto>`__
-  `Books for Developers </wiki/DevelBooks>`__
-  `Research papers related to Qubes </wiki/QubesResearch>`__

Contacts
--------

*Note: Please send all the questions regarding Qubes to the mailing list
(see below)*

Mailing list
~~~~~~~~~~~~

-  The group's email address: ``qubes-devel@googlegroups.com``
-  The Web interface:
   `​http://groups.google.com/group/qubes-devel <http://groups.google.com/group/qubes-devel>`__

To post to a group you don't need to subscribe, just send a message to
the group's email address. You can subscribe either through the web
interface (but then you need to create a google account), or by sending
an empty message to:

.. code:: wiki

    qubes-devel+subscribe@googlegroups.com

Architects & Core Developers
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-  Joanna Rutkowska <joanna at invisiblethingslab dot com> -
   architecture & project management

-  Rafal Wojtczuk <rafal at invisiblethingslab dot com> - architecture &
   system-level stuff

-  Marek Marczykowski <marmarek at mimuw dot edu dot pl> - core, and
   pretty much everything these days :)

Contributors
~~~~~~~~~~~~

-  TBD

Past developers
~~~~~~~~~~~~~~~

-  Tomasz Sterna <tomek at xiaoka dot com> - installer & gui

Press contact
~~~~~~~~~~~~~

-  Joanna Rutkowska <joanna at invisiblethingslab.com>

