|No image "qubes-arch-diagram-1.png" attached to QubesArchitecture|

Welcome to the Qubes OS Project
===============================

Qubes is an open-source operating system designed to provide strong
security for desktop computing. Qubes is based on Xen, the X Window
System, and Linux, and can run most Linux applications and utilize most
of the Linux drivers. Qubes **Release 1** was released in September
2012. Qubes **Release 2** is almost complete, with rc1 having been
released in April 2014. Qubes supports Windows-based AppVMs beginning
with Release 2.

-  `Getting Started </wiki/GettingStarted>`__
-  `Screenshots </wiki/QubesScreenshots>`__
-  `Architecture Overview </wiki/QubesArchitecture>`__, and also the
   more recent: `​Why Qubes OS is more than a bunch of
   VMs? <http://www.invisiblethingslab.com/resources/2014/Software_compartmentalization_vs_physical_separation.pdf>`__
-  `Qubes Security Goals </wiki/SecurityGoals>`__
-  `FAQ </wiki/UserFaq>`__
-  `User Documentation </wiki/UserDoc>`__
-  `​How is Qubes OS different
   from...? <http://theinvisiblethings.blogspot.com/2012/09/how-is-qubes-os-different-from.html>`__
-  Beyond Qubes R2 -- the `​Qubes Odyssey
   Framework <http://theinvisiblethings.blogspot.com/2013/03/introducing-qubes-odyssey-framework.html>`__

Recent News
-----------

-  ``Mar 21, 2013`` Introducing Qubes Odyssey Framework
   `​article <http://theinvisiblethings.blogspot.com/2013/03/introducing-qubes-odyssey-framework.html>`__
-  ``Jun 21, 2013`` Qubes OS R3 Alpha preview: Odyssey HAL in action!
   `​announcement <http://theinvisiblethings.blogspot.com/2013/06/qubes-os-r3-alpha-preview-odyssey-hal.html>`__
-  ``Nov 26, 2013`` Windows 7 seamless GUI integration coming to Qubes
   OS!
   `​article <http://theinvisiblethings.blogspot.com/2013/11/windows-7-seamless-gui-integration.html>`__
-  ``Dec 11, 2013`` Qubes OS R2 Beta 3 has been released!
   `​announcement <http://theinvisiblethings.blogspot.com/2013/12/qubes-r2-beta-3-has-been-released.html>`__
-  ``Feb 16, 2014`` Qubes OS selected as a finalist of Access Innovation
   Prize 2014 for Endpoint Security Solution
   `​announcement <https://www.accessnow.org/blog/2014/02/13/endpoint-security-prize-finalists-announced?utm_content=buffere803e&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer>`__
-  ``Mar 28, 2014`` `​Article about Qubes
   OS <http://www.economist.com/blogs/babbage/2014/03/computer-security>`__
   in The Economist
-  ``Apr 12, 2014`` `​Article about Qubes
   OS <https://pressfreedomfoundation.org/blog/2014/04/operating-system-can-protect-you-even-if-you-get-hacked>`__
   by the `​Freedom of the Press
   Foundation <https://pressfreedomfoundation.org/about/board>`__
-  ``Apr 21, 2014`` Qubes OS R2 rc1 has been released!
   `​announcement <http://theinvisiblethings.blogspot.com/2014/04/qubes-os-r2-rc1-has-been-released.html>`__
-  ``Jul 03, 2014`` ITL to present on Qubes OS at LinuxCon Europe: a
   keynote by Joanna Rutkowska and hands-on training by the core dev
   team! `​conference
   website <http://events.linuxfoundation.org/events/linuxcon-europe>`__
-  ``Jul 16, 2014`` Qubes Wiki now uses a CA-signed SSL cert (but you
   might also want to
   `​read <https://groups.google.com/forum/#!topic/qubes-users/LsDpKnwN6w8>`__
   also why this is mostly irrelevant)
-  ``Aug 06, 2014`` Qubes OS R2 rc2 has been released!
   `​announcement <http://theinvisiblethings.blogspot.com/2014/08/qubes-os-r2-rc2-debian-template-ssled.html>`__

.. |No image "qubes-arch-diagram-1.png" attached to QubesArchitecture| image:: /chrome/common/attachment.png
   :target: /wiki/QubesArchitecture
